services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
  web:
    image: web:local
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "3000:3000"
  backend:
    image: backend:local
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name:  backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis